eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    eureka自身不注册上去
    register-with-eureka: false
#  改变eureka上线率，开发环境使用
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761
management:
  server:
    servlet:
      context-path: /